name: test workflow

on: [push]

jobs:
  test-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Hello World"
      - name: Multiline command
        run: |
          npm --version
          node -v
  second-runner: 
    runs-on: ubuntu-latest
    steps: 
      - name: Who am I
        run: whoami
  sync-runner:
    runs-on: ubuntu-latest
    needs: test-job
    steps: 
      - run: echo "GGGGGGG"
    
    
      
